### PR TITLE
API for returning extra items returned by render server

### PR DESCRIPTION
**Pull request by sassanh**
This is required to be able to use things like [react-helmet](https://github.com/nfl/react-helmet).

### CODE REVIEW

**Comment by markfinger** [comment]
Thanks for that, it's a good idea.

Given the `extra` property is actually the output of the render server, the name "extra" seems a bit confusing in this context. Do you mind changing the `extra` variable&property to `data`?

If you can also update the docs (README.md) to add the property in https://github.com/markfinger/python-react#basic-usage, that'd be great.

**Comment by sassanh** [comment]
@markfinger OK, I changed the variable name and added the api to the README.md.

**Comment by markfinger** [comment]
Cool, looks good. 

Thanks, @sassanh 😄

**Comment by markfinger** [comment]
I've published your changes to PyPI as `react==4.2.0`. Let me know if you run into any issues, but otherwise thanks again for the PR.

**Comment by markfinger** [comment]
Just noticed a bug when `RENDER = False`. 

`react==4.2.1` includes a fix.

**Comment by sassanh** [comment]
Great, Thanks.

**Pull request merged**
