### PR TITLE
Added the possibility for a css property (in addition to the markup property)

### PR DESCRIPTION
**Pull request by anchpop**

### CODE REVIEW

**Comment by markfinger** [comment]
Thanks, but I'm not entirely confident of the benefit of this feature. Can you talk a bit about your use-cases and what you're trying to solve?

**Comment by anchpop** [comment]
@markfinger Sure. I basically only added this because I wanted to get [server side rendering of MaterialUI[(https://material-ui.com/guides/server-rendering/) working and this seemed like the cleanest way. Although I think a better route forward would be to have an extra field called `extraData` or something, where you could put whatever extra output you need in JSON format. Possibly having something similar for input to the server as well. If I add that to my copy I'll make another PR

**Comment by markfinger** [comment]
Yeah, a more general purpose variable for extra context might be better. 

So the styles are being generated in python code and you're passing them down the rendering pipeline? Is there a reason why you need to include the styles in the rendered markup, instead of using your template layer (or equivalent)?

I'm still not sure of the motivating details in the implementation tbh. If you could provide some code it might help. This seems a bit use-case specific, so I'm inclined towards suggesting that you maintain your own fork. This is a tiny and stable lib, so you're not really taking on anything approaching tech debt.

**Comment by sassanh** [comment]
@markfinger 
I guess this issue should be solved by https://github.com/markfinger/python-react/pull/87

**Comment by markfinger** [comment]
Yeah, good point, @sassanh.

@anchpop, the work in #87 allows for the response payload from the render server to be passed through the python part of the rendering pipeline. I think this should cover the python side of your usecase

**Pull request closed without merging**
