### PR TITLE
Example for integration with frontend using webpack

### PR DESCRIPTION
**Pull request by anantzoid**
While working with python-react, I had to spend some time in figuring out how this could be done in the cleanest way possible.
For beginners, who are using React and flask, this might act as a boilerplate, where `render_client.js`, like `render_server.js` can be used directly in their projects.
I've also shown how `forever` can be used to keep a watch on changes and restart the server in dev environment (see `scripts` in `package.json`).

### CODE REVIEW

**Comment by markfinger** [comment]
Cool, thanks for the PR. 

I'm a bit sick at the moment, but I'll try to find some time + energy over the next few days to take a look.

Thanks again!

**Comment by anantzoid** [comment]
Get well soon :)

**Comment by markfinger** [comment]
@anantzoid that's really cool and it's a great idea to use a watcher with the render server.

If you have time, do you mind adding some text to the README's `Usage in development` that describes your approach?

**Comment by anantzoid** [comment]
Will do. Thanks.

**Pull request merged**
